In [90]:
import pandas as pd
import joblib

In [2]:
 df = pd.read_csv("customerchurn.csv")

In [4]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes


In [5]:
df.shape

(7043, 21)

In [6]:
df.columns


Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   str    
 1   gender            7032 non-null   str    
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   str    
 4   Dependents        7032 non-null   str    
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   str    
 7   MultipleLines     7032 non-null   str    
 8   InternetService   7032 non-null   str    
 9   OnlineSecurity    7032 non-null   str    
 10  OnlineBackup      7032 non-null   str    
 11  DeviceProtection  7032 non-null   str    
 12  TechSupport       7032 non-null   str    
 13  StreamingTV       7032 non-null   str    
 14  StreamingMovies   7032 non-null   str    
 15  Contract          7032 non-null   str    
 16  PaperlessBilling  7032 non-null   str    
 17  PaymentMeth

In [8]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [12]:
# data cleaning 

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [18]:
df["TotalCharges"].isna().sum()

np.int64(11)

In [21]:
df[df["TotalCharges"].isna()][["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

,customerID,tenure,MonthlyCharges,TotalCharges,Churn


In [20]:
# delete row in TotalCharges column that null      
df = df.dropna(subset=["TotalCharges"])

In [32]:
df.shape

(7032, 20)

In [30]:
for col in df.select_dtypes(include="str").columns:
    print("\n", col)
    print(df[col].unique())


 customerID
<ArrowStringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str

 gender
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

 Partner
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 Dependents
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 PhoneService
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 MultipleLines
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

 InternetService
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

 OnlineSecurity
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

 OnlineBackup
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

 DeviceProtect

In [31]:
 df = df.drop("customerID", axis=1)

In [33]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,7032.000000,7032.000000,7032.000000,7032.000000
mean,0.162400,32.421786,64.798208,2283.300441
std,0.368844,24.545260,30.085974,2266.771362
min,0.000000,1.000000,18.250000,18.800000
25%,0.000000,9.000000,35.587500,401.450000
50%,0.000000,29.000000,70.350000,1397.475000
75%,0.000000,55.000000,89.862500,3794.737500
max,1.000000,72.000000,118.750000,8684.800000


In [36]:
# machine learing model
# X = Features → customer ki information
# y = Target → Churn



X = df.drop("Churn", axis=1)
y = df["Churn"]

In [40]:
y = y.map({"No": 0, "Yes": 1})

In [42]:
categorical_cols = X.select_dtypes(include="str").columns

print(categorical_cols)
print("Total categorical columns:", len(categorical_cols))

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')
Total categorical columns: 15


In [43]:
# ENCODIN )(ONE HOT ENCODING)

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True, dtype=int)

In [46]:
X.shape

(7032, 30)

In [47]:
X.head(5)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0


In [48]:
X.to_csv("X_data.csv", index=False)

In [49]:
# Split dataset into training and testing sets
# 80% data is used for model training and 20% for evaluation
# Stratify is applied to maintain the same churn distribution in both sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [57]:
# Initialize Logistic Regression model for customer churn prediction
# max_iter=1000 allows the model enough iterations to learn patterns
# Train the model using customer features (X_train) and churn labels (y_train)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)

model.fit(X_train, y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",5000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneOnly used for `solver` == 'sag', 'saga' or 'liblinear' to shuffle thedata. It has no effect on the other solvers.See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use i

In [54]:
X_train

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1413,0,65,94.55,6078.75,1,1,1,1,0,1,...,0,0,0,0,0,1,0,1,0,0
7003,0,26,35.75,1022.50,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3355,0,68,90.20,6297.65,0,1,0,1,0,1,...,0,0,0,0,0,1,0,1,0,0
4494,0,3,84.30,235.05,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3541,0,49,40.65,2070.75,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3451,1,65,70.95,4555.20,1,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,0
5123,1,15,75.30,1147.45,0,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
4135,0,36,92.90,3379.25,0,1,1,1,0,1,...,0,1,0,1,0,1,1,1,0,0
4249,0,10,65.90,660.05,0,1,1,1,0,0,...,0,0,0,1,1,0,1,0,0,1


In [61]:

y_pred = model.predict(X_test)

In [62]:
y_pred[:20]


array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

In [64]:
y_test.head()


974     0
619     0
4289    0
3721    1
4533    0
Name: Churn, dtype: int64

In [70]:
# Calculate model accuracy on test data

from sklearn.metrics import accuracy_score

accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)

print("Accuracy:", accuracy)

Accuracy: 80.45


In [71]:
# Compare actual and predicted values using confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[916 117]
 [158 216]]


In [72]:
# Generate detailed performance report for the model
# Shows Precision, Recall, F1-Score and Accuracy

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.58      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407



In [73]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled.shape)
print(X_test_scaled.shape)

(5625, 30)
(1407, 30)


In [74]:
# Train Logistic Regression model using scaled training data
# Scaled data helps the model learn better patterns
# Fit the model on training features and churn labels

from sklearn.linear_model import LogisticRegression

scaled_model = LogisticRegression(max_iter=1000)

scaled_model.fit(X_train_scaled, y_train)

print("Model trained successfully!")

Model trained successfully!


In [75]:
# Make predictions on scaled test data
# Display first 20 predicted churn values (0 = No, 1 = Yes)

y_pred_scaled = scaled_model.predict(X_test_scaled)

print(y_pred_scaled[:20])

[0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0]


In [76]:
from sklearn.metrics import accuracy_score

accuracy_scaled = accuracy_score(y_test, y_pred_scaled)

print("Scaled Model Accuracy:", accuracy_scaled * 100, "%")

Scaled Model Accuracy: 80.38379530916845 %


In [77]:
# Train Logistic Regression model with balanced class weights
# This helps the model pay equal attention to churn and non-churn customers
# Useful for handling class imbalance in the dataset

from sklearn.linear_model import LogisticRegression

balanced_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

balanced_model.fit(X_train_scaled, y_train)

print("Balanced model trained successfully!")

Balanced model trained successfully!


In [78]:
y_pred_balanced = balanced_model.predict(X_test_scaled)

print(y_pred_balanced[:20])

[0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 0]


In [79]:
from sklearn.metrics import accuracy_score

accuracy_balanced = accuracy_score(y_test, y_pred_balanced)

print("Balanced Model Accuracy:", accuracy_balanced * 100, "%")


Balanced Model Accuracy: 72.636815920398 %


In [80]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_balanced))


              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407



In [81]:
# Train a Decision Tree model for customer churn prediction
# max_depth=5 helps control tree size and reduce overfitting
# Use training data to learn patterns between customer features and churn

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

dt_model.fit(X_train, y_train)

print("Decision Tree trained successfully!")

Decision Tree trained successfully!


In [82]:
y_pred_dt = dt_model.predict(X_test)

print(y_pred_dt[:20])

[0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0]


In [83]:
from sklearn.metrics import accuracy_score

accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt * 100, "%")

Decision Tree Accuracy: 77.82515991471215 %


In [84]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.85      0.84      0.85      1033
           1       0.58      0.60      0.59       374

    accuracy                           0.78      1407
   macro avg       0.72      0.72      0.72      1407
weighted avg       0.78      0.78      0.78      1407



In [85]:
# Train a Random Forest model for customer churn prediction
# Random Forest combines multiple decision trees for better performance
# Use training data to learn customer behavior and churn patterns

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!


In [87]:
y_pred_rf = rf_model.predict(X_test)

print(y_pred_rf[:20])

[0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0]


In [88]:
from sklearn.metrics import accuracy_score

accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", accuracy_rf * 100, "%")

Random Forest Accuracy: 78.96233120113718 %


In [89]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1033
           1       0.63      0.52      0.57       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407



In [91]:
joblib.dump(model, "customer_churn_model.pkl")

print("Model saved successfully!")

Model saved successfully!


In [92]:
import os

print(os.path.exists("customer_churn_model.pkl"))

True


In [93]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

print("Imports successful!")

Imports successful!


In [94]:
raw_df = pd.read_csv("customerchurn.csv")

print(raw_df.shape)

(7043, 21)


In [95]:
raw_df["TotalCharges"] = pd.to_numeric(
    raw_df["TotalCharges"],
    errors="coerce"
)

print(raw_df["TotalCharges"].isna().sum())

11


In [96]:
raw_df = raw_df.dropna(subset=["TotalCharges"])

print(raw_df.shape)


(7032, 21)


In [97]:
X_raw = raw_df.drop(["Churn", "customerID"], axis=1)
y_raw = raw_df["Churn"].map({"No": 0, "Yes": 1})

print("X shape:", X_raw.shape)
print("y shape:", y_raw.shape)

X shape: (7032, 19)
y shape: (7032,)


In [98]:
categorical_cols_raw = X_raw.select_dtypes(include="object").columns
numerical_cols_raw = X_raw.select_dtypes(exclude="object").columns

print("Categorical columns:", len(categorical_cols_raw))
print("Numerical columns:", len(numerical_cols_raw))

print("\nCategorical:")
print(list(categorical_cols_raw))

print("\nNumerical:")
print(list(numerical_cols_raw))

Categorical columns: 15
Numerical columns: 4

Categorical:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']


C:\Users\Saroj Kumar\AppData\Local\Temp\ipykernel_14972\1151364574.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols_raw = X_raw.select_dtypes(include="object").columns


In [99]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), categorical_cols_raw),
        ("num", "passthrough", numerical_cols_raw)
    ]
)

print("Preprocessor created successfully!")

Preprocessor created successfully!
